### PR TITLE
Fragment migration splash

### PR DESCRIPTION
**Pull request by aholzapfel**

### CODE REVIEW

**Comment by moonlight200** [comment]
The build is failing due to a lint error, looks like one occurrence of  `activity!!` that should be replaced with `requireActivity()` like the other occurrences already have.

**Comment by moonlight200** [comment]
We could use #10 here for further examination

**Comment by Basler182** [comment]
For me, the merge worked locally without errors. 

We could also add to the _app\build.gradle_

```
android {
    lintOptions {
        abortOnError false
    }
}
```

But it would be better to analyze the lint report and solve it.

**Comment by moonlight200** [comment]
From the lint output:

> ../../../app: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)
> 
> Message: com.android.tools.lint.detector.api.Project.getGradleProjectModel()Lcom/android/builder/model/AndroidProject;
> 
> The crash seems to involve the detector com.google.firebase.installations.lint.IncompatibleIidVersionDetector.
> You can try disabling it with something like this:
>  ```
> android {
>   lintOptions {
>     disable "IncompatibleIidVersion"
>   }
> }
> ```
> 
> Stack: NoSuchMethodError:IncompatibleIidVersionDetector.beforeCheckEachProject(IncompatibleIidVersionDetector.kt:56)
> ←LintDriver.checkProject(LintDriver.kt:897)
> ←LintDriver.analyze(LintDriver.kt:426)
> ←LintCliClient.run(LintCliClient.kt:252)
> ←LintGradleClient.run(LintGradleClient.java:299)
> ←LintGradleExecution.runLint(LintGradleExecution.java:307)
> ←LintGradleExecution.lintAllVariants(LintGradleExecution.java:432)
> ←LintGradleExecution.analyze(LintGradleExecution.java:101)
> 
> You can set environment variable LINT_PRINT_STACKTRACE=true to dump a full stacktrace to stdout.

**Comment by moonlight200** [comment]
This seams to be an issue with the Firebase SDK, see [here](https://github.com/firebase/firebase-android-sdk/issues/1407)

**Review by moonlight200 — APPROVED** [review]
The app is stuck at the splash screen, but judging from the PR title, this is intended? (The other fragments/activities aren't created yet). Splash itself looks good, as does the rest :+1:

**Review by Basler182 — APPROVED** [review]
yes, now everything should work flawlessly

**Pull request merged**
